apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicase: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: springboot:latest
        ports:
        - containerPort: 8080
